name: Hello

on: [pull_request, issue_comment ]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        fetch-depth: 1
    - name: run python
      run: |
        echo ${{ github.event_name }} && echo ${{ github.event.action }}
      # env:
      #     GITHUB_EVENT: ${{ github.event }}
      #     GITHUB_EVENT_ANME : ${{ github.event }}
