name: Hello

on:
  pull_request:
    types: [opened, edited, reopened, synchronize]
  issue_comment:
    types: [created, edited, deleted]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        fetch-depth: 1
    - name: show info
      run: |
        echo ${{ github.event_name }} && echo ${{ github.event.action }} && cat ${{ github.event_path }}
    - name: show info 2
      run: |
        echo github.event.pull_request.merged = ${{ github.event.pull_request.merged }}
    - name: show info 3
      run: |
        echo github.event.issue.state = ${{ github.event.issue.state }}
